# Generated by Django 3.0.1 on 2022-11-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='book_size',
        ),
    ]
