# Generated by Django 3.2 on 2022-10-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20221022_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='has_sizes',
        ),
    ]
