# Generated by Django 3.2 on 2022-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='special',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
