# Generated by Django 3.0.1 on 2022-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20221110_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='site_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='site_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
